#!/bin/sh
set -e -u -o pipefail

cd /app/ovpn/config/ovpn_tcp

if [ -n "$REGION" ]; then
  set -- "$@" '--config' "${REGION}.nordvpn.com.tcp.ovpn"
else
  echo "No OpenVPN config found in `pwd`/${REGION}.nordvpn.com.tcp.ovpn. Exiting."
  exit 1
fi
if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
  echo "$USERNAME" > auth.conf
  echo "$PASSWORD" >> auth.conf
  chmod 600 auth.conf
  set -- "$@" '--auth-user-pass' 'auth.conf'
else
  echo "OpenVPN credentials not set. Exiting."
  exit 1
fi

openvpn "$@"
